type Interest = {
  name: string;
  category: string;
};
export const interests: Interest[] = [
  { name: 'Hiking', category: 'Outdoor' },
  { name: 'Camping', category: 'Outdoor' },
  { name: 'Cycling', category: 'Outdoor' },
  { name: 'Running', category: 'Outdoor' },
  { name: 'Fishing', category: 'Outdoor' },
  { name: 'Surfing', category: 'Outdoor' },
  { name: 'Rock Climbing', category: 'Outdoor' },
  { name: 'Swimming', category: 'Outdoor' },
  { name: 'Nature Walks', category: 'Outdoor' },
  { name: 'Stargazing', category: 'Outdoor' },

  { name: 'Cooking', category: 'Lifestyle' },
  { name: 'Baking', category: 'Lifestyle' },
  { name: 'Home Gardening', category: 'Lifestyle' },
  { name: 'Minimalism', category: 'Lifestyle' },
  { name: 'DIY Projects', category: 'Lifestyle' },
  { name: 'Interior Design', category: 'Lifestyle' },
  { name: 'Pet Care', category: 'Lifestyle' },
  { name: 'Sustainability', category: 'Lifestyle' },
  { name: 'Journaling', category: 'Lifestyle' },
  { name: 'Collecting', category: 'Lifestyle' },

  { name: 'Photography', category: 'Arts & Creativity' },
  { name: 'Drawing', category: 'Arts & Creativity' },
  { name: 'Painting', category: 'Arts & Creativity' },
  { name: 'Sculpting', category: 'Arts & Creativity' },
  { name: 'Calligraphy', category: 'Arts & Creativity' },
  { name: 'Graphic Design', category: 'Arts & Creativity' },
  { name: 'Film Making', category: 'Arts & Creativity' },
  { name: 'Crafting', category: 'Arts & Creativity' },
  { name: 'Tattoo Art', category: 'Arts & Creativity' },
  { name: 'Street Art', category: 'Arts & Creativity' },

  { name: 'Traveling', category: 'Travel & Culture' },
  { name: 'Road Trips', category: 'Travel & Culture' },
  { name: 'Cultural Festivals', category: 'Travel & Culture' },
  { name: 'Local Cuisine', category: 'Travel & Culture' },
  { name: 'Museum Visits', category: 'Travel & Culture' },
  { name: 'Historical Sites', category: 'Travel & Culture' },
  { name: 'Backpacking', category: 'Travel & Culture' },
  { name: 'Cruising', category: 'Travel & Culture' },
  { name: 'Beach Trips', category: 'Travel & Culture' },
  { name: 'City Exploration', category: 'Travel & Culture' },

  { name: 'Movies', category: 'Entertainment' },
  { name: 'TV Series', category: 'Entertainment' },
  { name: 'Podcasts', category: 'Entertainment' },
  { name: 'Stand-up Comedy', category: 'Entertainment' },
  { name: 'Theater', category: 'Entertainment' },
  { name: 'Live Concerts', category: 'Entertainment' },
  { name: 'Anime', category: 'Entertainment' },
  { name: 'K-Drama', category: 'Entertainment' },
  { name: 'Streaming', category: 'Entertainment' },
  { name: 'Board Games', category: 'Entertainment' },

  { name: 'Basketball', category: 'Sports' },
  { name: 'Football', category: 'Sports' },
  { name: 'Volleyball', category: 'Sports' },
  { name: 'Badminton', category: 'Sports' },
  { name: 'Tennis', category: 'Sports' },
  { name: 'Table Tennis', category: 'Sports' },
  { name: 'Boxing', category: 'Sports' },
  { name: 'Martial Arts', category: 'Sports' },
  { name: 'Yoga', category: 'Sports' },
  { name: 'Gym Workouts', category: 'Sports' },

  { name: 'Coding', category: 'Technology' },
  { name: 'Gaming', category: 'Technology' },
  { name: 'App Development', category: 'Technology' },
  { name: 'Web Design', category: 'Technology' },
  { name: 'Artificial Intelligence', category: 'Technology' },
  { name: 'Cybersecurity', category: 'Technology' },
  { name: 'Gadgets', category: 'Technology' },
  { name: 'Virtual Reality', category: 'Technology' },
  { name: '3D Printing', category: 'Technology' },
  { name: 'Blockchain', category: 'Technology' },

  { name: 'Reading', category: 'Education & Learning' },
  { name: 'Writing', category: 'Education & Learning' },
  { name: 'Language Learning', category: 'Education & Learning' },
  { name: 'Public Speaking', category: 'Education & Learning' },
  { name: 'History', category: 'Education & Learning' },
  { name: 'Science', category: 'Education & Learning' },
  { name: 'Philosophy', category: 'Education & Learning' },
  { name: 'Finance', category: 'Education & Learning' },
  { name: 'Marketing', category: 'Education & Learning' },
  { name: 'Psychology', category: 'Education & Learning' },

  { name: 'Volunteering', category: 'Community & Causes' },
  { name: 'Environmental Activism', category: 'Community & Causes' },
  { name: 'Animal Rescue', category: 'Community & Causes' },
  { name: 'Fundraising', category: 'Community & Causes' },
  { name: 'Blood Donation', category: 'Community & Causes' },
  { name: 'Social Work', category: 'Community & Causes' },
  { name: 'Nonprofit Support', category: 'Community & Causes' },
  { name: 'Disaster Relief', category: 'Community & Causes' },
  { name: 'Community Gardening', category: 'Community & Causes' },
  { name: 'Mentorship', category: 'Community & Causes' },

  { name: 'Stamp Collecting', category: 'Hobbies' },
  { name: 'Coin Collecting', category: 'Hobbies' },
  { name: 'Model Building', category: 'Hobbies' },
  { name: 'Puzzle Solving', category: 'Hobbies' },
  { name: 'Origami', category: 'Hobbies' },
  { name: 'Knitting', category: 'Hobbies' },
  { name: 'Scrapbooking', category: 'Hobbies' },
  { name: 'Birdwatching', category: 'Hobbies' },
  { name: 'Board Games', category: 'Hobbies' },
  { name: 'Collectible Card Games', category: 'Hobbies' },
];
